name: GM-Quantum-Advantage

on:
  schedule:
    - cron: "0 19 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Demonstrate Quantum Advantage
        run: |
          xcc config set REFRESH_TOKEN $REFRESH_TOKEN
          python gm-quantum-advantage.py
        env:
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
